#!/usr/bin/python3

import sys
from sympy import factorint

def factorize(n):
    return factorint(n)

def main(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize(number)
            print(f"{number}={'*'.join([f'{key}**{value}' for key, value in factors.items()])}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    main(file_path)
